AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  WeatherObservations:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/WeatherObservations
      Handler: WeatherObservations::WeatherObservations.Function::FunctionHandler
      Runtime: dotnet6
      Timeout: 10
      Environment:
        Variables:
          IS_DEBUG: !Ref IsDebug

Outputs:
  WeatherObservationsArn:
    Value: !GetAtt WeatherObservations.Arn