name: Deploy to Lambda

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: ./src/WeatherObservations

jobs:
  deploy-source:

    name: Deploy Lambda from source
    runs-on: ubuntu-latest

    env:
      working-directory: ./src/WeatherObservations
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: AWS CLI
        run: dotnet tool install --global Amazon.Lambda.Tools --version 5.6.4 
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Deploy to Lambda
        run: dotnet lambda deploy-function WeatherObservations
      
